#!/usr/bin/env node
/*
 * sign.mjs - Regenerate manifest.json.
 *
 * EDUCATIONAL SIMULATION - part of the Client Integrity Sandbox.
 *
 * This stands in for the signing step of a build pipeline. Run it after editing
 * any module under src/, or the loader will refuse to start:
 *
 *     node tools/sign.mjs
 *
 * A deliberate flaw is preserved here. The key is a constant in this file and
 * it is also written into manifest.json, which the client fetches - so the
 * client holds both the signature and the secret that produced it, and could
 * forge any signature it likes. That is not laziness; it is what always happens
 * when the verifier runs on the machine being verified. Real code signing
 * escapes this only by using asymmetric keys, where the client holds a public
 * key that can check a signature but not create one. Even then the conclusion
 * from Defense 4 stands unchanged: the signature describes the file at load
 * time and says nothing about memory afterwards.
 */

import { createHmac } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Must match MODULE_FILES in src/main.js.
const MODULES = ['rng', 'protocol', 'log', 'client', 'defenses', 'education', 'export', 'ui'];

// Not signed, and cannot be: these two are the loader itself, and a verifier
// cannot verify itself. See the header of src/main.js.
const UNSIGNED = ['hash.js', 'kernel.js', 'main.js', 'attacker.js', 'server.js'];

const KEY = 'client-integrity-sandbox/v1/demo-key';

const manifest = {
  _comment: 'Generated by tools/sign.mjs. Do not edit by hand. ' +
    'Unsigned by design: ' + UNSIGNED.join(', ') + '.',
  algorithm: 'HMAC-SHA256',
  key: KEY,
  generatedAt: new Date().toISOString(),
  modules: {}
};

for (const id of MODULES) {
  const path = join(ROOT, 'src', `${id}.js`);
  const source = await readFile(path, 'utf8');
  manifest.modules[id] = {
    file: `src/${id}.js`,
    bytes: Buffer.byteLength(source, 'utf8'),
    hmac: createHmac('sha256', KEY).update(source, 'utf8').digest('hex')
  };
  console.log(`  ${id.padEnd(10)} ${manifest.modules[id].hmac.slice(0, 16)}…  ` +
    `${manifest.modules[id].bytes} bytes`);
}

await writeFile(join(ROOT, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`\nSigned ${MODULES.length} modules into manifest.json`);
